queue_rules:
  - name: default
    merge_conditions:
      - "#approved-reviews-by >= 0"

pull_request_rules:
  - name: auto-queue
    conditions:
      - base=main
    actions:
      queue:
        name: default
