pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - label=auto-merge
    actions:
      merge:
        method: squash

queue_rules:
  - name: default
    conditions:
      - check-success=ci
